version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "bun" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
